name: .NET Core Desktop

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: windows-latest
    env:
      Solution_Name: CSFReader.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Get the tag
    - name: Get tag
      id: tag
      uses: devops-actions/action-get-tag@v1.0.1
      with:
        strip_v: true # Optional: Remove 'v' character from version
        default: v0.0.0 # Optional: Default version when tag not found
    
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    # Build the application
    - name: Build the application
      run: dotnet build -c Release
    
    # Generate the single binary
    - name: Generate single binary
      run: dotnet publish CSFReader\CSFReader.csproj -c Release -r win-x64 /p:SelfContained=true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true /p:DebugType=None /p:DebugSymbols=false /p:Version=${{steps.tag.outputs.tag}}  -o bin

    # Upload the artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: binary
        path: bin\CSFReader.exe

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      #Download the previous generated binary
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: binary

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: CSFReader/CSFReader
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
